name: Redeploy postdfm docs

on: [workflow_dispatch]

jobs:
  redeploy:
    name: Redeploy postdfm docs
    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v2

      - name: git checkout
        uses: actions/checkout@v2

      - name: git checkout spiltcoffee/postdfm
        uses: actions/checkout@v2
        with:
          repository: spiltcoffee/postdfm
          path: temp/postdfm

      - name: (postdfm) yarn ci
        run: yarn ci
        working-directory: temp/postdfm

      - name: rm docs
        run: rm -rf docs

      - name: cp docs
        run: cp -r temp/postdfm/docs docs

      - name: git add; git commit; git push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Redeploy postdfm docs"
          git push
