name: Redeploy votd-symbols

on: [workflow_dispatch]

jobs:
  redeploy:
    name: Redeploy votd-symbols
    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v2

      - name: git checkout
        uses: actions/checkout@v2

      - name: git checkout spiltcoffee/votd-symbols
        uses: actions/checkout@v2
        with:
          repository: spiltcoffee/votd-symbols
          path: temp/votd-symbols

      - name: (votd-symbols) yarn install
        run: yarn install --immutable
        working-directory: temp/votd-symbols

      - name: (votd-symbols) yarn build
        run: yarn build
        env:
          VOTD_SYMBOLS_PATH: d2/votd/symbols/
        working-directory: temp/votd-symbols

      - name: rm votd-symbols
        run: rm -rf d2/votd/symbols/

      - name: cp votd-symbols
        run: mkdir -p d2/votd/symbols/ && cp -r temp/votd-symbols/dist/* d2/votd/symbols/

      - name: github pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update votd-symbols
          title: "Update votd-symbols"
          body: "Automated redeployment of votd-symbols"
          branch: update/votd-symbols
          delete-branch: true
