name: Redeploy stopwatch

on: [workflow_dispatch]

jobs:
  redeploy:
    name: Redeploy stopwatch
    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v2

      - name: git checkout
        uses: actions/checkout@v2

      - name: git checkout spiltcoffee/stopwatch
        uses: actions/checkout@v2
        with:
          repository: spiltcoffee/stopwatch
          path: temp/stopwatch

      - name: (stopwatch) yarn install
        run: yarn install
        working-directory: temp/stopwatch

      - name: (stopwatch) yarn web
        run: yarn web
        working-directory: temp/stopwatch

      - name: rm stopwatch
        run: rm -rf stopwatch

      - name: cp stopwatch
        run: cp -r temp/stopwatch/out/web stopwatch

      - name: github pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update stopwatch
          title: 'Update stopwatch'
          body: 'Automated redeployment of stopwatch'
          branch: update/stopwatch
          delete-branch: true
