name: Redeploy stopwatch

on: [workflow_dispatch]

jobs:
  redeploy:
    name: Redeploy stopwatch
    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v2

      - name: git checkout
        uses: actions/checkout@v2

      - name: git checkout spiltcoffee/stopwatch
        uses: actions/checkout@v2
        with:
          repository: spiltcoffee/stopwatch
          path: temp/stopwatch

      - name: (stopwatch) yarn install
        run: yarn install
        working-directory: temp/stopwatch

      - name: (stopwatch) yarn web
        run: yarn web
        working-directory: temp/stopwatch

      - name: rm stopwatch
        run: rm -rf stopwatch

      - name: cp stopwatch
        run: cp -r temp/stopwatch/out stopwatch

      - name: git add; git commit; git push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Redeploy stopwatch"
          git push
