name: Redeploy Website

on: [workflow_dispatch]

jobs:
  redeploy:
    name: Redeploy Website
    runs-on: ubuntu-latest

    steps:
      - uses: srt32/git-actions@v0.0.3
      - name: git checkout
        uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: git commit && git push
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            docs/*
            stopwatch/*
          commit-msg: Redeploy Website
          github-token: ${{ secrets.GITHUB_TOKEN }}
