name: Redeploy postdfm docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [postdfm]

env:
  HUSKY: 0

jobs:
  redeploy:
    name: Redeploy postdfm docs
    runs-on: ubuntu-latest

    steps:
      - name: setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: git checkout
        uses: actions/checkout@v2

      - name: git checkout spiltcoffee/postdfm
        uses: actions/checkout@v2
        with:
          repository: spiltcoffee/postdfm
          path: temp/postdfm

      - name: (postdfm) yarn install
        run: yarn install
        working-directory: temp/postdfm

      - name: (postdfm) yarn ci
        run: yarn ci
        working-directory: temp/postdfm

      - name: rm docs
        run: rm -rf docs

      - name: cp docs
        run: cp -r temp/postdfm/docs docs

      - name: github pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update postdfm docs
          title: "Update postdfm docs"
          body: "Automated redeployment of postdfm docs"
          branch: update/postdfm
          delete-branch: true
